### ISSUE TITLE
onOpen事件里get不到值

### ISSUE THREAD

**Issue by 188700679** [weakcc/hf-chat#1]
http://192.168.31.204:9501/?username=hello

我看你在代碼裏：
 if (isset($request->get['username']) && !empty($request->get['username'])) {

但是实际我传：
http://192.168.31.204:9501/?username=hello
获取不到

var_dump($request->get)
值等于null

那么，我该如何传username值呢

**Comment by weakcc** [comment]
https://wiki.swoole.com/#/start/start_ws_server 请看下这个 WebSocket 服务器

**Comment by weakcc** [comment]
http://192.168.31.204:9501/?username=hello 属于 HTTP 服务器
你应该在 js 里面实现 Websocket 连接。如：
var wsServer = 'ws://127.0.0.1:9502?username=hello';
var websocket = new WebSocket(wsServer);
websocket.onopen = function (evt) {
console.log("Connected to WebSocket server.");
};
...

**Comment by weakcc** [comment]
...
